apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: networks.simulator.io
spec:
  group: simulator.io
  versions:
    - name: v1
      subresources:
        status: {}
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                enabled: 
                    type: boolean
            status:
              type: object
              properties:
                enabled: 
                    type: boolean
  scope: Namespaced
  names:
    plural: networks
    singular: network
    kind: Network
    shortNames:
        - net
