apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: delay-cas
spec:
  hosts:
  - cas.keramik-load-with-network-errors-for-2-36-1.svc.cluster.local
  http:
  - match:
    - port: 8081
    fault:
      delay:
        percent: 100
        fixedDelay: 10s
    route:
    - destination:
        host: cas.keramik-load-with-network-errors-for-2-36-1.svc.cluster.local
