FROM public.ecr.aws/r5b3e0r5/3box/rust-builder:latest as chef

RUN mkdir -p /home/builder/keramik/
WORKDIR /home/builder/keramik/

FROM chef AS planner
COPY . .
RUN cargo chef prepare --bin operator --recipe-path recipe.json

FROM chef AS builder
COPY --from=planner /home/builder/keramik/recipe.json recipe.json

# Build dependencies - this is the caching Docker layer!
RUN cargo chef cook --release --recipe-path recipe.json

# Build application
COPY . .
RUN cargo build -p keramik-operator --release --locked

FROM ubuntu:latest

COPY --from=builder /home/builder/keramik/target/release/keramik-operator /usr/bin

ENTRYPOINT ["/usr/bin/keramik-operator"]
