---
namespace: keramik

resources:
  - ./manifests/operator.yaml

#
#
# Uncomment either the latest or development section
#
#

# Uncomment for running latest
#
# Additionally ensure that ./k8s/operator/manifests/operator.yaml uses Always as the imagePullPolicy
#
images:
  - name: samika98/operator
    newName: samika98/operator
    newTag: lgen

# Uncomment for development
#
# Additionally ensure that ./k8s/operator/manifests/operator.yaml uses IfNotPresent as the imagePullPolicy
#
#images:
#  - name: keramik/operator
#    newTag: dev
