apiVersion: "keramik.3box.io/v1alpha1"
kind: Network
metadata:
  name: small
spec:
  replicas: 2
  bootstrap:
    image: runner:dev
    imagePullPolicy: IfNotPresent
  cas:
    ipfs:
      go: {} 
  ceramic:
    - ipfs:
        rust: {} 
      env:
        CERAMIC_PUBSUB_QPS_LIMIT: "1000"