[package]
name = "expect-patch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diffy = "0.3.0"
once_cell = "1.17.1"
expect-test = "1"
