{
 "title": "keys",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "keys inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ceramic_store_key_insert_count_total[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}}"
    },
    {
     "expr": "rate(recon_protocol_message_flush_count_total[$__rate_interval])",
     "legendFormat": "{{k8s_pod_name}} - flush"
    }
   ]
  },
  {
   "title": "keys inserted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "ceramic_store_key_insert_count_total",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(ceramic_store_store_query_durations_sum{k8s_pod_name=\"ceramic-0-0\"} / ceramic_store_store_query_durations_count)",
     "legendFormat": "{{name}} - {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "queries",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(ceramic_store_store_query_durations_sum{k8s_pod_name=\"ceramic-0-1\"} / ceramic_store_store_query_durations_count)",
     "legendFormat": "{{name}} - {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(ceramic_store_store_query_durations_count[$__rate_interval])",
     "legendFormat": "{{name}} - {{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "c1 api",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "ceramic_api_request_durations_sum / ceramic_api_request_durations_count",
     "legendFormat": "{{k8s_pod_name}} - {{path}}"
    }
   ]
  }
 ]
}