---
namespace: keramik-keyresult

resources:
  - ./opentelemetry.yaml
  - ./jaeger.yaml
  - ./prometheus.yaml

configMapGenerator:
  - name: otel-config
    files:
      - ./otel-config.yaml
  - name: prom-config
    files:
      - ./prom-config.yaml

