---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: otel
  namespace: default
  labels:
    app: otel
spec:
  replicas: 1
  serviceName: otel
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      serviceAccountName: monitoring-service-account
      securityContext:
        # Explicitly set a filesystem group to allow writing to mounts
        fsGroup: 2000
      containers:
        - name: opentelemetry
          image: public.ecr.aws/r5b3e0r5/3box/otelcol:latest
          imagePullPolicy: Always
          command:
            - /otelcol-custom
            - --config=/config/otel-config.yaml
          ports:
            - containerPort: 4317
              name: otlp-receiver
            - containerPort: 9090
              name: prom-metrics
            - containerPort: 8888
              name: self-metrics
          resources:
            limits:
              cpu: 1
              memory: 1Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 500m
              memory: 1Gi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
            - name: otel-data
              mountPath: /data
              readOnly: false
      volumes:
        - name: config
          configMap:
            name: otel-config
        - name: otel-data
          persistentVolumeClaim:
            claimName: otel-data
  volumeClaimTemplates:
    - metadata:
        name: otel-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
---
kind: Service
apiVersion: v1
metadata:
  name: otel
  namespace: default
  labels:
    app: otel
spec:
  ports:
    - port: 4317
      targetPort: 4317
      protocol: TCP
      name: otlp-receiver
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: prom-metrics
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: self-metrics
  selector:
    app: otel
  type: ClusterIP


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: monitoring-cluster-role

rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount

metadata:
  name: monitoring-service-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding

metadata:
  name: monitoring-cluster-role-binding

roleRef:
  kind: ClusterRole
  name: monitoring-cluster-role
  apiGroup: rbac.authorization.k8s.io

subjects:
  - kind: ServiceAccount
    name: monitoring-service-account
    namespace: default

