---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: keramik-0
spec:
  hostname: debug
  subdomain: goose
  containers:
    - name: container
      image: ubuntu
      command:
        - /bin/bash
        - -c
        - sleep infinity
