global:
  scrape_interval: 10s
  scrape_timeout: 5s

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    honor_labels: true
    static_configs:
      - targets:
        - 'localhost:9090'
        - 'otel:9090'
        - 'otel:8888'
