---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: prometheus
  namespace: default
  labels:
    app: prometheus
spec:
  replicas: 1
  serviceName: prometheus
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.42.0
          command:
            - /bin/prometheus
            - --web.enable-lifecycle
            - --config.file=/config/prom-config.yaml
          ports:
            - containerPort: 9090
              name: webui
          resources:
            limits:
              cpu: 250m
              memory: 1Gi
              ephemeral-storage: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
              ephemeral-storage: 1Gi
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: prom-config
