# Define a set of jobs that run a simulations against the network.
---
# Create a service so that the workers can find the manager via DNS
apiVersion: v1
kind: Service
metadata:
  name: goose
spec:
  selector:
    name: goose
  clusterIP: None
  ports:
  - name: manager
    port: 5115
---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-manager
spec:
  template:
    metadata:
      labels:
        name: goose
    spec:
      hostname: manager
      subdomain: goose
      containers:
      - name: manager
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_MANAGER
            value: 'true'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_TARGET_PEER
            value: '0'
          - name: SIMULATE_NONCE
            value: '1516760'
          - name: SIMULATE_USERS
            value: '1000'
          - name: SIMULATE_RUN_TIME
            value: '10m'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-worker-0
spec:
  template:
    spec:
      containers:
      - name: worker
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: RUST_BACKTRACE
            value: '1'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_TARGET_PEER
            value: '0'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_NONCE
            value: '10986711'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-worker-1
spec:
  template:
    spec:
      containers:
      - name: worker
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_TARGET_PEER
            value: '1'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_NONCE
            value: '10986711'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4


---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-worker-2
spec:
  template:
    spec:
      containers:
      - name: worker
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_TARGET_PEER
            value: '2'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_NONCE
            value: '10986711'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4


---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-worker-3
spec:
  template:
    spec:
      containers:
      - name: worker
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_TARGET_PEER
            value: '3'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_NONCE
            value: '10986711'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4

---
apiVersion: batch/v1
kind: Job
metadata:
  name: simulate-worker-4
spec:
  template:
    spec:
      containers:
      - name: worker
        image: keramik/runner
        imagePullPolicy: IfNotPresent
        command:
          - "/usr/bin/keramik-runner"
          - "simulate"
        env:
          - name: RUNNER_OTLP_ENDPOINT
            value: 'http://otel:4317'
          - name: RUST_LOG
            value: 'info,keramik_runner=trace'
          - name: SIMULATE_SCENARIO
            value: 'ceramic-write-only'
          - name: SIMULATE_TARGET_PEER
            value: '4'
          - name: SIMULATE_PEERS_PATH
            value: '/keramik-peers/peers.json'
          - name: SIMULATE_NONCE
            value: '10986711'
          - name: DID_KEY
            value: 'did:key:z6Mkqn5jbycThHcBtakJZ8fHBQ2oVRQhXQEdQk5ZK2NDtNZA'
          - name: DID_PRIVATE_KEY
            value: '86dce513cf0a37d4acd6d2c2e00fe4b95e0e655ca51e1a890808f5fa6f4fe65a'
        volumeMounts:
          - name: keramik-peers
            mountPath: /keramik-peers
      volumes:
        - name: keramik-peers
          configMap:
            name: "keramik-peers"
            defaultMode: 0755
      restartPolicy: Never
  backoffLimit: 4
