[package]
name = "keramik-runner"
description = "Utility binary for performing various jobs to simulate Ceramic networks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
cid = "0.9"
clap.workspace = true
goose = { version = "0.16", features = ["gaggle"] }
keramik-common.workspace = true
libipld = "0.16.0"
multiaddr.workspace = true
multibase.workspace = true
multihash.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
prometheus-client = "0.19"
rand = "0.8.5"
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
tracing-log.workspace = true
