[package]
name = "keramik-runner"
description = "Utility binary for performing various jobs to simulate Ceramic networks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
ceramic-http-client = { git = "https://github.com/3box/ceramic-http-client-rs.git", branch = "main", default-features = false }
ceramic-pocket-knife = { git = "https://github.com/nathanielc/ceramic-pocket-knife.git", branch = "main", default-features = false, features = [
    "ceramic",
] }
cid = "0.10"
clap.workspace = true
goose = { version = "0.16", features = ["gaggle"] }
keramik-common = { workspace = true, features = ["telemetry"] }
libipld = "0.16.0"
multihash.workspace = true
opentelemetry.workspace = true
rand = "0.8.5"
redis = { version = "0.23.2", features = ["tokio-comp"] }
reqwest.workspace = true
schemars = "0.8.12"
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing-log.workspace = true
tracing.workspace = true
multibase.workspace = true
tdigest = "0.2.3"
tokio-util = { version = "0.7.10", features = ["rt"] }
futures = "0.3.29"
tokio-stream = "0.1.14"
signal-hook = "0.3.17"
signal-hook-tokio = { version = "0.3.1", features = ["futures-v0_3"] }
