[package]
name = "keramik-operator"
description = "K8s operator binary for automating Ceramic networks"
version = "0.1.0"
edition = "2021"

[[bin]]
doc = false
name = "crdgen"
path = "src/crdgen.rs"

[[bin]]
name = "keramik-operator"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
env_logger.workspace = true
keramik-common.workspace = true
kube = { version = "0.82", default-features = true, features = [
    "derive",
    "runtime",
] }
k8s-openapi = { version = "0.18", default-features = false, features = [
    "v1_23",
] }
futures = "0.3"
serde = "1"
serde_json = "1.0"
schemars = "0.8"
thiserror = "1"
serde_yaml = "0.9.21"
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
