name: On demand Docker Image Build

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        description: "Tag name will be prefaced with 'on-demand-'."
env:
  IMAGE_REPO: public.ecr.aws/r5b3e0r5/3box

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Public ECR
        uses: docker/login-action@v2
        with:
            registry: public.ecr.aws
            username: ${{ secrets.AWS_ACCESS_KEY_ID }}
            password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        env:
            AWS_REGION: us-east-1
      - name: Set Final Tag
        run: echo "TAG=on-demand-${{ inputs.tag_name }}" >> "$GITHUB_ENV"

      - name: Build Docker runner Image
        run: |
          docker buildx build --load -t $IMAGE_REPO/keramik-runner:$TAG --target runner .
          docker push $IMAGE_REPO/keramik-runner:$TAG

      - name: Build Docker operator Image
        run: |
          docker buildx build --load -t $IMAGE_REPO/keramik-operator:$TAG --target operator .
          docker push $IMAGE_REPO/keramik-operator:$TAG

      - name: Print Image names
        run: |
          echo $IMAGE_REPO/keramik-runner:$TAG
          echo $IMAGE_REPO/keramik-operator:$TAG

